### ISSUE TITLE
this is based

### ISSUE THREAD

**Issue by settwi** [abnerbog/levenberg-marquardt-method#2]
see title
that's all

(also--very nice implementation, similar to [XSPEC](https://heasarc.gsfc.nasa.gov/xanadu/xspec/)!)

**Comment by abnerbog** [comment]
Could you elaborate further on the meaning of the issue title? I've never used XSPEC but looks like an awesome library ! Thanks for sending over.

**Comment by settwi** [comment]
It just means that it’s good haha. Sorry this isn’t really an issue, just a way of saying thank you!
